projectName: EditDidWhat
projectUrl: https://joelpurra.com/projects/editdidwhat/
projectRedirectBaseUrl: https://joelpurra.com/projects/editdidwhat
projectGithub: https://github.com/joelpurra/editdidwhat
projectStackoverflow: https://stackoverflow.com/search?q=editdidwhat
